#!/bin/bash

printf '#!/bin/bash
if [[ `pgrep -fl iperf` ]]; then
  echo "iperf server is already running on $i";
  sudo killall iperf
  echo "iperf server is restarting";
else
  echo "iperf was not running - Starting iperf...";
fi

' > run-server

if [[ $2 == "tcp" ]]; then
  echo "sudo iperf -s -p 51 &" >> run-server
elif [[ $2 == "udp" ]]; then
  echo "sudo iperf -s -u -p 51 &" >> run-server
elif [[ $2 == "all" ]]; then
  echo "sudo iperf -s -p 51 &" >> run-server
  echo "sudo iperf -s -u -p 51 &" >> run-server
fi

chmod u+x run-server

#for i in `nova list | grep $1 | awk '{print $12}' | sed 's/.*=//'`; do
for i in `neutron floatingip-list | awk '{print $6}'`; do
  #Checks for iperf on each server and installs if necessary
  if [[ `ssh -o StrictHostKeyChecking=no ubuntu@$i 'which iperf'` ]]; then
    echo "iperf is installed on $i";
  else
    ssh -o StrictHostKeyChecking=no ubuntu@$i 'wget http://iperf.fr/download/iperf_2.0.5/iperf_2.0.5-2_amd64 ; chmod +x iperf_2.0.5-2_amd64 ; sudo mv iperf_2.0.5-2_amd64 /usr/bin/iperf'
  fi



  scp ./run-server ubuntu@$i:~ 
  ssh -o StrictHostKeyChecking=no ubuntu@$i 'echo "$(expr $(date +%M) + 1) $(date +%H) * * * /home/ubuntu/run-server" > mycron; crontab mycron'
done

cat run-server
rm run-server
